<?php

/**
 * @file
 * Adds conditional CSS from the .info file.
 */

/**
 * Implements hook_page_build().
 */
function conditional_styles_page_build(&$page) {
  $theme_handler = \Drupal::service('theme_handler');
  $themes        = $theme_handler->listInfo(); 
  foreach ($themes as $theme) {
    $theme_path = drupal_get_path($theme->type, $theme->name);
    if (isset($theme->info['stylesheets-conditional']) && $theme->status) {
      foreach ($theme->info['stylesheets-conditional'] as $condition => $medias) {
        foreach ($medias as $media => $stylesheets) {
	        foreach ($stylesheets as $stylesheet) {
	        	$full_path = $theme_path . '/' . $stylesheet;
	          $page['#attached']['css'][$full_path] = array(
          		'group' => CSS_THEME,
          		'weight' => 999,
          		'media' => $media,
          		'every_page' => TRUE,
              'browsers' => array(
                'IE'  => $condition,
                '!IE' => strpos($condition, '!IE') === FALSE ? FALSE : TRUE,
              ),
	          );
	        }
        }
      }
    }
  }
}
